### ISSUE TITLE
Finalize and assign chapters

### ISSUE THREAD

**Issue by LucyMcGowan** [malcolmbarrett/causal-inference-in-R#2]
https://github.com/LucyMcGowan/causal-inference-in-R/blob/7daf4f2275c265cb06b8416a281995a186218dda/index.Rmd#L16-L81

**Comment by malcolmbarrett** [comment]
Likely split g-computation into its own chapter + cover loss to follow-up

**Comment by malcolmbarrett** [comment]
We need to add missingness. I also think maybe we should do a separate "Other types of exposures" chapter (splitting out the continuous section we already wrote) that covers continuous and categorical exposures. After the outcome model chapter

**Comment by malcolmbarrett** [comment]
Now organized via project board
