### ISSUE TITLE
Set up netlify and connect to domain

### ISSUE THREAD

**Issue by malcolmbarrett** [malcolmbarrett/causal-inference-in-R#5]
As set up in #4

**Comment by tgerke** [comment]
GH Actions is failing on Netlify auth (and might be burning up your Actions minutes unnecessarily 😬 ). @LucyMcGowan I believe as repo owner the GH Secrets are owned by you, so I'm assuming you'll need to link/re-link those tokens. Lmk if there's anything I can do to help though.

**Comment by LucyMcGowan** [comment]
Oh dear, I know almost nothing about GitHub Actions - @malcolmbarrett I think you set this up, is there something I need to do?

**Comment by malcolmbarrett** [comment]
Yeah, you'll need to set up credentials for the repo: https://github.com/r-lib/actions/tree/master/examples#managing-secrets

I wouldn't worry about this burning through minutes, tho!

**Comment by malcolmbarrett** [comment]
GHA workflow now deploys correctly to netlify, and we're up and running at https://www.r-causal.org/!
