### ISSUE TITLE
Idea: Data Chapter

### ISSUE THREAD

**Issue by malcolmbarrett** [malcolmbarrett/causal-inference-in-R#51]
The tidymodels book has a chapter specific to the main dataset, including EDA. 

https://www.tmwr.org/ames.html

We might do this with at least the Disney data

**Comment by EmilHvitfeldt** [comment]
We did the same in smltar.com and it worked pretty well https://smltar.com/appendixdata.html

**Comment by malcolmbarrett** [comment]
Formalized in #67
