### ISSUE TITLE
Select data set(s)

### ISSUE THREAD

**Issue by tgerke** [malcolmbarrett/causal-inference-in-R#9]
1. Whole game example
2. Thread to continue through propensity based models
3. Survival data: EHR data set. Right heart catheterization (Lucy https://hbiostat.org/data/repo/rhc.html)
4. Mediation (might work with data set 2.)

To explore:
Tidy Tuesday may have candidates
Our World in Data
Sports data(?). Sabermetrics available, but baseball may be too US centric. 
Econ! Andrew Heiss has examples? Education, employment
Psych data for mediation. Wellness/happiness (general community survey? personality studies)

A simulation exercise would be useful for demonstrating the "correct" answer and how close estimates get to identifying truth. Easier for these not to be medical.

**Comment by tgerke** [comment]
For EHR data, the [Synthea app](https://synthetichealth.github.io/synthea/) may be a good option. You can build out [custom state transition modules](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework) which will simulate EHR data according to a distribution we assign - could be great for checking model validity against known parameters.

**Comment by LucyMcGowan** [comment]
We can pull in Disney data from here: https://touringplans.com/walt-disney-world/crowd-calendar#DataSets

**Comment by LucyMcGowan** [comment]
Disney data is here: www.github.com/LucyMcGowan/touringplans

```
devtools::install_github("LucyMcGowan/touringplans")
```
